version: 2
jobs:
  build:
    docker:
      - image: mono
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Seedwork.Test